// Mocks generated by Mockito 5.4.5 from annotations
// in flowit_app/test/attendees_sync_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flowit_app/core/result.dart' as _i2;
import 'package:flowit_app/data/services/local_storage_service.dart' as _i3;
import 'package:hive_flutter/hive_flutter.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LocalStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorageService extends _i1.Mock
    implements _i3.LocalStorageService {
  @override
  _i4.Future<_i2.Result<void>> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #initialize,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #initialize,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<List<T>>> getAll<T>(String? boxName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [boxName],
        ),
        returnValue:
            _i4.Future<_i2.Result<List<T>>>.value(_FakeResult_0<List<T>>(
          this,
          Invocation.method(
            #getAll,
            [boxName],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<List<T>>>.value(_FakeResult_0<List<T>>(
          this,
          Invocation.method(
            #getAll,
            [boxName],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<T>>>);

  @override
  _i4.Future<_i2.Result<void>> put<T>(
    String? boxName,
    String? key,
    T? item,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            boxName,
            key,
            item,
          ],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #put,
            [
              boxName,
              key,
              item,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #put,
            [
              boxName,
              key,
              item,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<T?>> get<T>(
    String? boxName,
    String? key,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [
            boxName,
            key,
          ],
        ),
        returnValue: _i4.Future<_i2.Result<T?>>.value(_FakeResult_0<T?>(
          this,
          Invocation.method(
            #get,
            [
              boxName,
              key,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<T?>>.value(_FakeResult_0<T?>(
          this,
          Invocation.method(
            #get,
            [
              boxName,
              key,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Result<T?>>);

  @override
  _i4.Future<_i2.Result<void>> delete(
    String? boxName,
    String? key,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [
            boxName,
            key,
          ],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #delete,
            [
              boxName,
              key,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #delete,
            [
              boxName,
              key,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Stream<_i5.BoxEvent> getStream(String? boxName) => (super.noSuchMethod(
        Invocation.method(
          #getStream,
          [boxName],
        ),
        returnValue: _i4.Stream<_i5.BoxEvent>.empty(),
        returnValueForMissingStub: _i4.Stream<_i5.BoxEvent>.empty(),
      ) as _i4.Stream<_i5.BoxEvent>);

  @override
  _i4.Future<_i2.Result<void>> clear(String? boxName) => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [boxName],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #clear,
            [boxName],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #clear,
            [boxName],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<void>> fixCorruptedData() => (super.noSuchMethod(
        Invocation.method(
          #fixCorruptedData,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #fixCorruptedData,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #fixCorruptedData,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<void>> clearAllData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #clearAllData,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #clearAllData,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<void>> emergencyReset() => (super.noSuchMethod(
        Invocation.method(
          #emergencyReset,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #emergencyReset,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #emergencyReset,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> debugAllBoxes() => (super.noSuchMethod(
        Invocation.method(
          #debugAllBoxes,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
