// Mocks generated by Mockito 5.4.5 from annotations
// in flowit_app/test/domain_feature_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flowit_app/core/result.dart' as _i2;
import 'package:flowit_app/data/models/caldav_account.dart' as _i9;
import 'package:flowit_app/data/models/task_calendar.dart' as _i5;
import 'package:flowit_app/data/repositories/account_repository.dart' as _i8;
import 'package:flowit_app/data/repositories/calendar_repository.dart' as _i3;
import 'package:flowit_app/data/services/local_storage_service.dart' as _i6;
import 'package:hive_flutter/hive_flutter.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CalendarRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalendarRepository extends _i1.Mock
    implements _i3.CalendarRepository {
  MockCalendarRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<List<_i5.TaskCalendar>>> getAll() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i5.TaskCalendar>>>.value(
            _FakeResult_0<List<_i5.TaskCalendar>>(
          this,
          Invocation.method(
            #getAll,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i5.TaskCalendar>>>);

  @override
  _i4.Future<_i2.Result<_i5.TaskCalendar?>> getById(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getById,
          [uid],
        ),
        returnValue: _i4.Future<_i2.Result<_i5.TaskCalendar?>>.value(
            _FakeResult_0<_i5.TaskCalendar?>(
          this,
          Invocation.method(
            #getById,
            [uid],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i5.TaskCalendar?>>);

  @override
  _i4.Future<_i2.Result<_i5.TaskCalendar?>> getByPath(String? path) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByPath,
          [path],
        ),
        returnValue: _i4.Future<_i2.Result<_i5.TaskCalendar?>>.value(
            _FakeResult_0<_i5.TaskCalendar?>(
          this,
          Invocation.method(
            #getByPath,
            [path],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i5.TaskCalendar?>>);

  @override
  _i4.Future<_i2.Result<void>> save(_i5.TaskCalendar? calendar) =>
      (super.noSuchMethod(
        Invocation.method(
          #save,
          [calendar],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #save,
            [calendar],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<void>> delete(String? uid) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [uid],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #delete,
            [uid],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Stream<List<_i5.TaskCalendar>> watchCalendars() => (super.noSuchMethod(
        Invocation.method(
          #watchCalendars,
          [],
        ),
        returnValue: _i4.Stream<List<_i5.TaskCalendar>>.empty(),
      ) as _i4.Stream<List<_i5.TaskCalendar>>);

  @override
  _i4.Future<_i2.Result<List<_i5.TaskCalendar>>> getProjectCalendars() =>
      (super.noSuchMethod(
        Invocation.method(
          #getProjectCalendars,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i5.TaskCalendar>>>.value(
            _FakeResult_0<List<_i5.TaskCalendar>>(
          this,
          Invocation.method(
            #getProjectCalendars,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i5.TaskCalendar>>>);

  @override
  _i4.Future<_i2.Result<List<_i5.TaskCalendar>>> getCalendarsByDomain(
          String? domain) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCalendarsByDomain,
          [domain],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i5.TaskCalendar>>>.value(
            _FakeResult_0<List<_i5.TaskCalendar>>(
          this,
          Invocation.method(
            #getCalendarsByDomain,
            [domain],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i5.TaskCalendar>>>);

  @override
  _i4.Future<_i2.Result<List<String>>> getUniqueDomains() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUniqueDomains,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<List<String>>>.value(
            _FakeResult_0<List<String>>(
          this,
          Invocation.method(
            #getUniqueDomains,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<String>>>);

  @override
  _i4.Future<_i2.Result<void>> renameDomain(
    String? oldDomain,
    String? newDomain,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #renameDomain,
          [
            oldDomain,
            newDomain,
          ],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #renameDomain,
            [
              oldDomain,
              newDomain,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<Map<String, int>>> getDomainStatistics() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDomainStatistics,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<Map<String, int>>>.value(
            _FakeResult_0<Map<String, int>>(
          this,
          Invocation.method(
            #getDomainStatistics,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<Map<String, int>>>);

  @override
  _i4.Future<_i2.Result<List<_i5.TaskCalendar>>> getCalendarsWithoutDomain() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCalendarsWithoutDomain,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i5.TaskCalendar>>>.value(
            _FakeResult_0<List<_i5.TaskCalendar>>(
          this,
          Invocation.method(
            #getCalendarsWithoutDomain,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i5.TaskCalendar>>>);
}

/// A class which mocks [LocalStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorageService extends _i1.Mock
    implements _i6.LocalStorageService {
  MockLocalStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<void>> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #initialize,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<List<T>>> getAll<T>(String? boxName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [boxName],
        ),
        returnValue:
            _i4.Future<_i2.Result<List<T>>>.value(_FakeResult_0<List<T>>(
          this,
          Invocation.method(
            #getAll,
            [boxName],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<T>>>);

  @override
  _i4.Future<_i2.Result<void>> put<T>(
    String? boxName,
    String? key,
    T? item,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            boxName,
            key,
            item,
          ],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #put,
            [
              boxName,
              key,
              item,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<T?>> get<T>(
    String? boxName,
    String? key,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [
            boxName,
            key,
          ],
        ),
        returnValue: _i4.Future<_i2.Result<T?>>.value(_FakeResult_0<T?>(
          this,
          Invocation.method(
            #get,
            [
              boxName,
              key,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Result<T?>>);

  @override
  _i4.Future<_i2.Result<void>> delete(
    String? boxName,
    String? key,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [
            boxName,
            key,
          ],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #delete,
            [
              boxName,
              key,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Stream<_i7.BoxEvent> getStream(String? boxName) => (super.noSuchMethod(
        Invocation.method(
          #getStream,
          [boxName],
        ),
        returnValue: _i4.Stream<_i7.BoxEvent>.empty(),
      ) as _i4.Stream<_i7.BoxEvent>);

  @override
  _i4.Future<_i2.Result<void>> clear(String? boxName) => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [boxName],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #clear,
            [boxName],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<void>> fixCorruptedData() => (super.noSuchMethod(
        Invocation.method(
          #fixCorruptedData,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #fixCorruptedData,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<void>> clearAllData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #clearAllData,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<void>> emergencyReset() => (super.noSuchMethod(
        Invocation.method(
          #emergencyReset,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #emergencyReset,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> debugAllBoxes() => (super.noSuchMethod(
        Invocation.method(
          #debugAllBoxes,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.Result<List<String>>> getAllDomains() => (super.noSuchMethod(
        Invocation.method(
          #getAllDomains,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<List<String>>>.value(
            _FakeResult_0<List<String>>(
          this,
          Invocation.method(
            #getAllDomains,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<String>>>);

  @override
  _i4.Future<_i2.Result<void>> addDomain(String? domain) => (super.noSuchMethod(
        Invocation.method(
          #addDomain,
          [domain],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #addDomain,
            [domain],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<void>> removeDomain(String? domain) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeDomain,
          [domain],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #removeDomain,
            [domain],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<bool>> domainExists(String? domain) =>
      (super.noSuchMethod(
        Invocation.method(
          #domainExists,
          [domain],
        ),
        returnValue: _i4.Future<_i2.Result<bool>>.value(_FakeResult_0<bool>(
          this,
          Invocation.method(
            #domainExists,
            [domain],
          ),
        )),
      ) as _i4.Future<_i2.Result<bool>>);

  @override
  _i4.Future<_i2.Result<void>> renameDomain(
    String? oldDomain,
    String? newDomain,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #renameDomain,
          [
            oldDomain,
            newDomain,
          ],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #renameDomain,
            [
              oldDomain,
              newDomain,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);
}

/// A class which mocks [AccountRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountRepository extends _i1.Mock implements _i8.AccountRepository {
  MockAccountRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<List<_i9.CaldavAccount>>> getAll() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i9.CaldavAccount>>>.value(
            _FakeResult_0<List<_i9.CaldavAccount>>(
          this,
          Invocation.method(
            #getAll,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i9.CaldavAccount>>>);

  @override
  _i4.Future<_i2.Result<_i9.CaldavAccount?>> getActiveAccount() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveAccount,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<_i9.CaldavAccount?>>.value(
            _FakeResult_0<_i9.CaldavAccount?>(
          this,
          Invocation.method(
            #getActiveAccount,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i9.CaldavAccount?>>);

  @override
  _i4.Future<_i2.Result<void>> save(_i9.CaldavAccount? account) =>
      (super.noSuchMethod(
        Invocation.method(
          #save,
          [account],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #save,
            [account],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<void>> delete(String? accountId) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [accountId],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #delete,
            [accountId],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<void>> setActiveAccount(String? accountId) =>
      (super.noSuchMethod(
        Invocation.method(
          #setActiveAccount,
          [accountId],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #setActiveAccount,
            [accountId],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<bool>> hasActiveAccount() => (super.noSuchMethod(
        Invocation.method(
          #hasActiveAccount,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<bool>>.value(_FakeResult_0<bool>(
          this,
          Invocation.method(
            #hasActiveAccount,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<bool>>);
}
