// Mocks generated by Mockito 5.4.5 from annotations
// in flowit_app/test/sync_delete_diagnosis.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flowit_app/core/result.dart' as _i2;
import 'package:flowit_app/data/models/task.dart' as _i5;
import 'package:flowit_app/data/repositories/task_repository.dart' as _i3;
import 'package:flowit_app/data/services/sync_service.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRepository extends _i1.Mock implements _i3.TaskRepository {
  @override
  _i4.Future<_i2.Result<List<_i5.Task>>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i5.Task>>>.value(
            _FakeResult_0<List<_i5.Task>>(
          this,
          Invocation.method(
            #getAll,
            [],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.Result<List<_i5.Task>>>.value(
            _FakeResult_0<List<_i5.Task>>(
          this,
          Invocation.method(
            #getAll,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i5.Task>>>);

  @override
  _i4.Future<_i2.Result<_i5.Task?>> getById(String? uid) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [uid],
        ),
        returnValue:
            _i4.Future<_i2.Result<_i5.Task?>>.value(_FakeResult_0<_i5.Task?>(
          this,
          Invocation.method(
            #getById,
            [uid],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<_i5.Task?>>.value(_FakeResult_0<_i5.Task?>(
          this,
          Invocation.method(
            #getById,
            [uid],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i5.Task?>>);

  @override
  _i4.Future<_i2.Result<List<_i5.Task>>> getByProject(String? projectUid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByProject,
          [projectUid],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i5.Task>>>.value(
            _FakeResult_0<List<_i5.Task>>(
          this,
          Invocation.method(
            #getByProject,
            [projectUid],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.Result<List<_i5.Task>>>.value(
            _FakeResult_0<List<_i5.Task>>(
          this,
          Invocation.method(
            #getByProject,
            [projectUid],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i5.Task>>>);

  @override
  _i4.Future<_i2.Result<List<_i5.Task>>> getTasksWithDueDate(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTasksWithDueDate,
          [date],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i5.Task>>>.value(
            _FakeResult_0<List<_i5.Task>>(
          this,
          Invocation.method(
            #getTasksWithDueDate,
            [date],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.Result<List<_i5.Task>>>.value(
            _FakeResult_0<List<_i5.Task>>(
          this,
          Invocation.method(
            #getTasksWithDueDate,
            [date],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i5.Task>>>);

  @override
  _i4.Future<_i2.Result<List<_i5.Task>>> getTasksWithoutDueDate() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTasksWithoutDueDate,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i5.Task>>>.value(
            _FakeResult_0<List<_i5.Task>>(
          this,
          Invocation.method(
            #getTasksWithoutDueDate,
            [],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.Result<List<_i5.Task>>>.value(
            _FakeResult_0<List<_i5.Task>>(
          this,
          Invocation.method(
            #getTasksWithoutDueDate,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i5.Task>>>);

  @override
  _i4.Future<_i2.Result<List<_i5.Task>>> getUnregisteredTasks() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnregisteredTasks,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i5.Task>>>.value(
            _FakeResult_0<List<_i5.Task>>(
          this,
          Invocation.method(
            #getUnregisteredTasks,
            [],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.Result<List<_i5.Task>>>.value(
            _FakeResult_0<List<_i5.Task>>(
          this,
          Invocation.method(
            #getUnregisteredTasks,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i5.Task>>>);

  @override
  _i4.Future<_i2.Result<void>> save(_i5.Task? task) => (super.noSuchMethod(
        Invocation.method(
          #save,
          [task],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #save,
            [task],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #save,
            [task],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<void>> delete(String? uid) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [uid],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #delete,
            [uid],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #delete,
            [uid],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Stream<List<_i5.Task>> watchTasks() => (super.noSuchMethod(
        Invocation.method(
          #watchTasks,
          [],
        ),
        returnValue: _i4.Stream<List<_i5.Task>>.empty(),
        returnValueForMissingStub: _i4.Stream<List<_i5.Task>>.empty(),
      ) as _i4.Stream<List<_i5.Task>>);
}

/// A class which mocks [SyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncService extends _i1.Mock implements _i6.SyncService {
  @override
  _i4.Stream<_i6.SyncStatus> get statusStream => (super.noSuchMethod(
        Invocation.getter(#statusStream),
        returnValue: _i4.Stream<_i6.SyncStatus>.empty(),
        returnValueForMissingStub: _i4.Stream<_i6.SyncStatus>.empty(),
      ) as _i4.Stream<_i6.SyncStatus>);

  @override
  _i4.Stream<double> get progressStream => (super.noSuchMethod(
        Invocation.getter(#progressStream),
        returnValue: _i4.Stream<double>.empty(),
        returnValueForMissingStub: _i4.Stream<double>.empty(),
      ) as _i4.Stream<double>);

  @override
  _i6.SyncStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i6.SyncStatus.idle,
        returnValueForMissingStub: _i6.SyncStatus.idle,
      ) as _i6.SyncStatus);

  @override
  bool get isBackgroundSyncRunning => (super.noSuchMethod(
        Invocation.getter(#isBackgroundSyncRunning),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isBackgroundSyncing => (super.noSuchMethod(
        Invocation.getter(#isBackgroundSyncing),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.Future<_i2.Result<void>> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #initialize,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #initialize,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  void startPeriodicSync() => super.noSuchMethod(
        Invocation.method(
          #startPeriodicSync,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void stopPeriodicSync() => super.noSuchMethod(
        Invocation.method(
          #stopPeriodicSync,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<_i2.Result<_i6.SyncResult>> syncNow() => (super.noSuchMethod(
        Invocation.method(
          #syncNow,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<_i6.SyncResult>>.value(
            _FakeResult_0<_i6.SyncResult>(
          this,
          Invocation.method(
            #syncNow,
            [],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.Result<_i6.SyncResult>>.value(
            _FakeResult_0<_i6.SyncResult>(
          this,
          Invocation.method(
            #syncNow,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i6.SyncResult>>);

  @override
  _i4.Future<_i2.Result<void>> queueSyncOperation(
    _i6.SyncOperation? operation,
    String? itemId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #queueSyncOperation,
          [
            operation,
            itemId,
            data,
          ],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #queueSyncOperation,
            [
              operation,
              itemId,
              data,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #queueSyncOperation,
            [
              operation,
              itemId,
              data,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
