stages:
  - prepare
  - version
  - test
  - build
  - release

variables:
  FLUTTER_VERSION: "3.35.2"
  CUSTOM_IMAGE_NAME: "$CI_REGISTRY_IMAGE/flutter-build-env"
  CUSTOM_IMAGE_TAG: "$FLUTTER_VERSION"
  ANDROID_TOOL_VERSION_X: "34"
  ANDROID_TOOL_VERSION: "${ANDROID_TOOL_VERSION_X}.0.0"
  FLATPAK_RUNTIME_VERSION: "48"
  FLATPAK_BUILD_IMAGE: "$CI_REGISTRY_IMAGE/build-flatpak"
update_version:
  stage: version
  image: alpine:latest
  rules:
    - if: '$CI_COMMIT_TAG'
  before_script:
    - apk add --no-cache yq
  script:
    # Strip leading v from tags like v1.2.3
    - TAG="${CI_COMMIT_TAG#v}"
    # Overwrite pubspec.yaml version
    - yq e -i ".version = \"${TAG}\"" pubspec.yaml
    - echo "Updated pubspec.yaml version to ${TAG}"
    - cat pubspec.yaml | grep "version:"
  artifacts:
    paths:
      - pubspec.yaml
    expire_in: 1 week

#build_base_image:
#  stage: prepare
#  image: docker:latest
#  tags:
#    - docker-build
#  services:
#    - docker:dind
#  script:
#    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#    - >
#      docker build
#      --build-arg FLUTTER_VERSION=$FLUTTER_VERSION
#      --build-arg ANDROID_TOOL_VERSION_X=$ANDROID_TOOL_VERSION_X
#      --build-arg ANDROID_TOOL_VERSION=$ANDROID_TOOL_VERSION
#      -t $CUSTOM_IMAGE_NAME:$CUSTOM_IMAGE_TAG -f CI_scripts/linux/Dockerfile .
#    - docker push $CUSTOM_IMAGE_NAME:$CUSTOM_IMAGE_TAG
#  rules:
#    - if: '$CI_COMMIT_TAG'
#      when: never
#    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
#      changes:
#        - .gitlab-ci.yml
#      when: always
#    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
#      when: manual

#build_windows_base_image:
#  stage: prepare
#  image: docker:latest
#  tags:
#    - windows
#  services:
#    - docker:dind
#  variables:
#    WINDOWS_CUSTOM_IMAGE_NAME: "$CI_REGISTRY_IMAGE/flutter-windows-build-env"
#    WINDOWS_CUSTOM_IMAGE_TAG: "$FLUTTER_VERSION"
#  script:
#    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#    - docker build -t $WINDOWS_CUSTOM_IMAGE_NAME:$WINDOWS_CUSTOM_IMAGE_TAG -f CI_scripts/windows/Dockerfile .
#    - docker push $WINDOWS_CUSTOM_IMAGE_NAME:$WINDOWS_CUSTOM_IMAGE_TAG
#  rules:
#    - if: '$CI_COMMIT_TAG'
#      when: never
#    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
#      changes:
#        - .gitlab-ci.yml
#        - CI_scripts/windows/Dockerfile
#      when: always
#    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
#      when: manual

test:
  stage: test
  image: $CUSTOM_IMAGE_NAME:$CUSTOM_IMAGE_TAG
  needs:
    - job: update_version
      artifacts: true
      optional: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  script:
    - flutter pub get
    - dart run build_runner build --delete-conflicting-outputs
    - flutter gen-l10n
    - flutter test --timeout=10m

build_appimage:
  stage: build
  image: $CUSTOM_IMAGE_NAME:$CUSTOM_IMAGE_TAG
  needs:
    - job: update_version
      artifacts: true
    - job: test
  rules:
    - if: '$CI_COMMIT_TAG'
  before_script:
    - echo "APPIMAGE_JOB_ID=$CI_JOB_ID" > build.env
    - echo "CI_PIPELINE_IID=$CI_PIPELINE_IID" >> build.env
    - echo "CI_COMMIT_TAG=$CI_COMMIT_TAG" >> build.env
  script:
    - bash CI_scripts/linux/build_app_image.sh $CI_COMMIT_TAG $CI_PIPELINE_IID "build/linux/x64/release/towdow_app-$CI_COMMIT_TAG.AppImage"
  artifacts:
    paths:
      - "build/linux/x64/release/towdow_app-$CI_COMMIT_TAG.AppImage"
    expire_in: 1 week
    reports:
      dotenv: build.env

build_snapcraft:
  stage: build
  tags:
    - snapcraft
  rules:
    - if: '$CI_COMMIT_TAG'
  needs:
    - job: build_appimage
      artifacts: true
    - job: test
  before_script:
    - echo "SNAPCRAFT_JOB_ID=$CI_JOB_ID" > build.env
    - echo "CI_COMMIT_TAG=$CI_COMMIT_TAG" >> build.env
  script:
    - snapcraft --version
    - bash CI_scripts/linux/build_snapcraft_from_appimage.sh
  artifacts:
    when: always
    paths:
      - towdow_${CI_COMMIT_TAG}_amd64.snap
    expire_in: 1 week
    reports:
      dotenv: build.env


build_flatpak:
  stage: build
  image: "$FLATPAK_BUILD_IMAGE:${FLATPAK_RUNTIME_VERSION}"
  tags:
    - flatpak
  rules:
    - if: '$CI_COMMIT_TAG'
  needs:
    - job: build_appimage
      artifacts: true
    - job: test
  cache:
    key: flatpak-$CI_COMMIT_REF_SLUG
    paths:
      - .flatpak/
      - .flatpak-builder/
  artifacts:
    when: always
    expire_in: 2 weeks
    paths:
      - repo/
      - towdow.$CI_COMMIT_TAG.flatpak
      - build-logs/
    reports:
      dotenv: build.env
  before_script:
    - sed -i "s/0\.0\.0/${CI_COMMIT_TAG}/g" app.towdow.TowDow.yaml
    - sed -i "s/0\.0\.0/${CI_COMMIT_TAG}/g" CI_scripts/linux/flatpak/data/app.towdow.TowDow.metainfo.xml
    - echo "FLATPAK_JOB_ID=$CI_JOB_ID" > build.env
    - echo "CI_COMMIT_TAG=$CI_COMMIT_TAG" >> build.env
  script:
    - flatpak-builder --repo=repo build-dir app.towdow.TowDow.yaml  --force-clean --default-branch=stable
    - flatpak build-bundle repo towdow.$CI_COMMIT_TAG.flatpak app.towdow.TowDow stable
    - ostree --repo=repo refs

build_android:
  stage: build
  image: $CUSTOM_IMAGE_NAME:$CUSTOM_IMAGE_TAG
  tags:
    - android-build
  needs:
    - job: update_version
      artifacts: true
    - job: test
  rules:
    - if: '$CI_COMMIT_TAG'
  before_script:
    - echo "ANDROID_JOB_ID=$CI_JOB_ID" > build.env
    - echo "CI_PIPELINE_IID=$CI_PIPELINE_IID" >> build.env
    - echo "CI_COMMIT_TAG=$CI_COMMIT_TAG" >> build.env
  script:
    - KEY_PROPERTIES_PASSWORD=$(echo $KEY_PROPERTIES_PASSWORD_BASE64 | base64 -d)
    - echo "storePassword=__key_pass__" > android/key.properties
    - echo "keyPassword=__key_pass__" >> android/key.properties
    - echo "keyAlias=upload" >> android/key.properties
    - echo "storeFile=${CI_PROJECT_DIR}/upload-keystore.jks" >> android/key.properties
    - sed -i "s/__key_pass__/${KEY_PROPERTIES_PASSWORD}/g" android/key.properties
#    - echo $JKS_BASE_64 > certfile_base64
#    - openssl enc -d -base64 -in certfile_base64 -out ${CI_PROJECT_DIR}/upload-keystore.jks
    - echo -n ${JKS_BASE_64} | base64 -d > ${CI_PROJECT_DIR}/upload-keystore.jks
    - flutter pub get
    - dart run build_runner build --delete-conflicting-outputs
    - flutter gen-l10n
    - flutter build apk --release --build-name=$CI_COMMIT_TAG --build-number=$CI_PIPELINE_IID
    - mv build/app/outputs/flutter-apk/app-release.apk "build/app/outputs/flutter-apk/app-release-$CI_COMMIT_TAG.apk"
    - flutter build appbundle --release --build-name=$CI_COMMIT_TAG --build-number=$CI_PIPELINE_IID
    - mv build/app/outputs/bundle/release/app-release.aab "build/app/outputs/bundle/release/app-release-$CI_COMMIT_TAG.aab"
  artifacts:
    paths:
      - "build/app/outputs/flutter-apk/app-release-$CI_COMMIT_TAG.apk"
      - "build/app/outputs/bundle/release/app-release-$CI_COMMIT_TAG.aab"
    expire_in: 1 week
    reports:
      dotenv: build.env

build_windows:
  stage: build
  tags:
    - windows-build
  needs:
    - job: update_version
      artifacts: true
    - job: test
  rules:
    - if: '$CI_COMMIT_TAG'
  before_script:
    - echo "WINDOWS_JOB_ID=$env:CI_JOB_ID" > build.env
  script:
    # prevent fatal: detected dubious ownership in repository at 'C:/flutter'
    - git config --global --add safe.directory C:/flutter
    - flutter pub get
    - dart run build_runner build --delete-conflicting-outputs
    - flutter gen-l10n
    - echo "tag $env:CI_COMMIT_TAG"
    - echo "build name $env:CI_COMMIT_TAG"
    - echo "build number:$env:CI_PIPELINE_IID"
    - flutter build windows --release --build-name="$env:CI_COMMIT_TAG" --build-number="$env:CI_PIPELINE_IID"
    # now package with Inno bundle to havoid msi paid certificates https://hahouari.medium.com/easy-windows-installers-for-flutter-apps-with-inno-bundle-2ec9b05d2c75
    - powershell -ExecutionPolicy Bypass -File .\CI_scripts\windows\install_inno.ps1
    - dart run inno_bundle:build --release --app-version "$env:CI_COMMIT_TAG" --no-gen-publisher --no-app
    - Compress-Archive -Path build/windows/x64/runner/Release/* -DestinationPath "build/windows/x64/runner/Release/towdow_app-$env:CI_COMMIT_TAG.zip"
    # build msix
    - $version = "$env:CI_COMMIT_TAG.0"
    - dart run msix:create --install-certificate false --version $version --store
    - Copy-Item "build\windows\x64\runner\Release\towdow_app.msix" -Destination "build\windows\x64\runner\Release\towdow_app-$env:CI_COMMIT_TAG.msix"
    - dir "build/windows/x64/runner/Release/towdow_app-$env:CI_COMMIT_TAG.zip"
    - dir "build/windows/x64/installer/Release/TowdowApp-x86_64-$env:CI_COMMIT_TAG-Installer.exe"
  artifacts:
    paths:
      - "build/windows/x64/runner/Release/towdow_app-$CI_COMMIT_TAG.zip"
      - "build/windows/x64/installer/Release/TowdowApp-x86_64-$CI_COMMIT_TAG-Installer.exe"
      - "build/windows/x64/runner/Release/towdow_app-$CI_COMMIT_TAG.msix"
      - "build/windows/x64/runner/Release/towdow_app.msix"
    expire_in: 1 week
    reports:
      dotenv: build.env

prepare_release:
  stage: build
  image:
    name: alpine/git
    entrypoint: [""]
  rules:
    - if: '$CI_COMMIT_TAG'
  script:
    - git fetch origin "refs/tags/$CI_COMMIT_TAG:refs/tags/$CI_COMMIT_TAG"
    - git tag -l --format='%(contents)' "$CI_COMMIT_TAG" > release_notes.txt
  artifacts:
    paths:
      - release_notes.txt

build_web:
  stage: build
  image: $CUSTOM_IMAGE_NAME:$CUSTOM_IMAGE_TAG
  needs:
    - job: update_version
      artifacts: true
    - job: test
  rules:
    - if: '$CI_COMMIT_TAG'
  before_script:
    - echo "WEB_JOB_ID=$CI_JOB_ID" > build.env
    - echo "CI_PIPELINE_IID=$CI_PIPELINE_IID" >> build.env
    - echo "CI_COMMIT_TAG=$CI_COMMIT_TAG" >> build.env
  script:
    - flutter pub get
    - dart run build_runner build --delete-conflicting-outputs
    - flutter gen-l10n
    # TODO: solve wam warning https://docs.flutter.dev/platform-integration/web/wasm
    - flutter build web --release
    - tar zcf "build/web_${CI_COMMIT_TAG}.tar.gz" build/web
  artifacts:
    paths:
      - "build/web_${CI_COMMIT_TAG}.tar.gz"
    expire_in: 1 week
    reports:
      dotenv: build.env


release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: build_appimage
      artifacts: true
    - job: build_android
      artifacts: true
    - job: build_windows
      artifacts: true
    - job: build_web
      artifacts: true
    - job: build_snapcraft
      artifacts: true
    - job: build_flatpak
      artifacts: true
    - job: prepare_release
      artifacts: true
  rules:
    - if: '$CI_COMMIT_TAG'
  script:
    - echo "Releasing $CI_COMMIT_TAG"
  release:
    tag_name: "$CI_COMMIT_TAG"
    name: "Release $CI_COMMIT_TAG"
    description: "./release_notes.txt"
    assets:
      links:
        - name: "Towdow AppImage"
          url: "$CI_PROJECT_URL/-/jobs/$APPIMAGE_JOB_ID/artifacts/file/build/linux/x64/release/towdow_app-$CI_COMMIT_TAG.AppImage"
        - name: "Towdow Snapcraft"
          url: "$CI_PROJECT_URL/-/jobs/$SNAPCRAFT_JOB_ID/artifacts/file/towdow_${CI_COMMIT_TAG}_amd64.snap"
        - name: "Towdow flatpak"
          url: "$CI_PROJECT_URL/-/jobs/$FLATPAK_JOB_ID/artifacts/file/towdow.$CI_COMMIT_TAG.flatpak"
        - name: "Towdow Android APK"
          url: "$CI_PROJECT_URL/-/jobs/$ANDROID_JOB_ID/artifacts/file/build/app/outputs/flutter-apk/app-release-$CI_COMMIT_TAG.apk"
        - name: "Towdow Android AAB"
          url: "$CI_PROJECT_URL/-/jobs/$ANDROID_JOB_ID/artifacts/file/build/app/outputs/bundle/release/app-release-$CI_COMMIT_TAG.aab"
        - name: "Towdow Windows Installer"
          url: "$CI_PROJECT_URL/-/jobs/$WINDOWS_JOB_ID/artifacts/file/build/windows/x64/installer/Release/TowdowApp-x86_64-$CI_COMMIT_TAG-Installer.exe"
        - name: "Towdow Windows zip"
          url: "$CI_PROJECT_URL/-/jobs/$WINDOWS_JOB_ID/artifacts/file/build/windows/x64/runner/Release/towdow_app-$CI_COMMIT_TAG.zip"
        - name: "Towdow web"
          url: "$CI_PROJECT_URL/-/jobs/$WEB_JOB_ID/artifacts/file/build/web_${CI_COMMIT_TAG}.tar.gz"
        - name: "TowDow Windows msix"
          url: "$CI_PROJECT_URL/-/jobs/$WINDOWS_JOB_ID/artifacts/file/build/windows/x64/runner/Release/towdow_app-$CI_COMMIT_TAG.msix"
        - name: "TowDow Windows msix no version"
          url: "$CI_PROJECT_URL/-/jobs/$WINDOWS_JOB_ID/artifacts/file/build/windows/x64/runner/Release/towdow_app.msix"

deploy_web:
  stage: release
  image: debian:bullseye-slim
  needs:
    - job: build_web
      artifacts: true
  rules:
    - if: '$CI_COMMIT_TAG'
  before_script:
    - apt-get update && apt-get install -y openssh-client
    # Save and decode the base64 key into a file
    - echo "${SSH_PRIVATE_KEY}" | base64 -d > /tmp/ssh_key
    - chmod 600 /tmp/ssh_key
    # Start ssh-agent and add the key
    - eval "$(ssh-agent -s)"
    - ssh-add /tmp/ssh_key
    # verify the key is loaded
    - ssh-add -l
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H web.towdow.app >> ~/.ssh/known_hosts
  script:
    - tar -zxf "build/web_${CI_COMMIT_TAG}.tar.gz"
    - scp -r build/web debian@web.towdow.app:flutter_web/build/
    - ssh debian@web.towdow.app "docker restart flutter-web"

deploy_snapcraft:
  stage: release
  tags:
    - snapcraft
  needs:
    - job: build_snapcraft
      artifacts: true
  rules:
    - if: '$CI_COMMIT_TAG'
  before_script:
    - export SNAPCRAFT_STORE_CREDENTIALS=${SNAPCRAFT_LOGIN}
    - snapcraft whoami
  script:
    - snapcraft upload --release=stable towdow_${CI_COMMIT_TAG}_amd64.snap