stages:
  - prepare
  - build
  - release

variables:
  APPIMAGE_OUTPUT: "build/linux/x64/release/towdow_app.AppImage"
  APK_OUTPUT: "build/app/outputs/flutter-apk/app-release.apk"
  FLUTTER_VERSION: "3.32.5"
  CUSTOM_IMAGE_NAME: "$CI_REGISTRY_IMAGE/flutter-build-env"
  CUSTOM_IMAGE_TAG: "$FLUTTER_VERSION"
  ANDROID_TOOL_VERSION_X: "34"
  ANDROID_TOOL_VERSION: "${ANDROID_TOOL_VERSION_X}.0.0"

build_base_image:
  stage: prepare
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - >
      docker build
      --build-arg FLUTTER_VERSION=$FLUTTER_VERSION
      --build-arg ANDROID_TOOL_VERSION_X=$ANDROID_TOOL_VERSION_X
      --build-arg ANDROID_TOOL_VERSION=$ANDROID_TOOL_VERSION
      -t $CUSTOM_IMAGE_NAME:$CUSTOM_IMAGE_TAG -f CI_scripts/linux/Dockerfile .
    - docker push $CUSTOM_IMAGE_NAME:$CUSTOM_IMAGE_TAG
  rules:
    - if: '$CI_COMMIT_TAG'
      when: never
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      changes:
        - .gitlab-ci.yml
      when: always
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: manual

build_appimage:
  stage: build
  image: $CUSTOM_IMAGE_NAME:$CUSTOM_IMAGE_TAG
  rules:
    - if: '$CI_COMMIT_TAG'
  script:
    - CI_COMMIT_TAG_CLEAN=$(echo $CI_COMMIT_TAG | sed 's/^v//')
    - bash CI_scripts/linux/build_app_image.sh $CI_COMMIT_TAG_CLEAN $CI_PIPELINE_IID
  artifacts:
    paths:
      - $APPIMAGE_OUTPUT
    expire_in: 1 hour

build_android:
  stage: build
  image: $CUSTOM_IMAGE_NAME:$CUSTOM_IMAGE_TAG
  rules:
    - if: '$CI_COMMIT_TAG'
  script:
    - CI_COMMIT_TAG_CLEAN=$(echo $CI_COMMIT_TAG | sed 's/^v//')
    - flutter pub get
    - flutter build apk --release --build-name=$CI_COMMIT_TAG_CLEAN --build-number=$CI_PIPELINE_IID
  artifacts:
    paths:
      - $APK_OUTPUT
    expire_in: 1 hour

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs: [build_appimage, build_android]
  rules:
    - if: '$CI_COMMIT_TAG'
  script:
    - echo "Releasing $CI_COMMIT_TAG"
  release:
    tag_name: "$CI_COMMIT_TAG"
    name: "Release $CI_COMMIT_TAG"
    description: "Automated release for tag $CI_COMMIT_TAG"
    assets:
      links:
        - name: "Towdow AppImage"
          url: "$CI_PROJECT_URL/-/jobs/$CI_JOB_ID/artifacts/file/$APPIMAGE_OUTPUT"
        - name: "Towdow Android APK"
          url: "$CI_PROJECT_URL/-/jobs/$CI_JOB_ID/artifacts/file/$APK_OUTPUT"
