// Mocks generated by Mockito 5.4.5 from annotations
// in towdow_app/test/viewmodels/attendee_commands_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:towdow_app/core/result.dart' as _i2;
import 'package:towdow_app/data/models/task.dart' as _i5;
import 'package:towdow_app/data/repositories/task_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRepository extends _i1.Mock implements _i3.TaskRepository {
  @override
  _i4.Future<_i2.Result<List<_i5.Task>>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i5.Task>>>.value(
            _FakeResult_0<List<_i5.Task>>(
          this,
          Invocation.method(
            #getAll,
            [],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.Result<List<_i5.Task>>>.value(
            _FakeResult_0<List<_i5.Task>>(
          this,
          Invocation.method(
            #getAll,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i5.Task>>>);

  @override
  _i4.Future<_i2.Result<_i5.Task?>> getById(String? uid) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [uid],
        ),
        returnValue:
            _i4.Future<_i2.Result<_i5.Task?>>.value(_FakeResult_0<_i5.Task?>(
          this,
          Invocation.method(
            #getById,
            [uid],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<_i5.Task?>>.value(_FakeResult_0<_i5.Task?>(
          this,
          Invocation.method(
            #getById,
            [uid],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i5.Task?>>);

  @override
  _i4.Future<_i2.Result<List<_i5.Task>>> getByProject(String? projectUid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByProject,
          [projectUid],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i5.Task>>>.value(
            _FakeResult_0<List<_i5.Task>>(
          this,
          Invocation.method(
            #getByProject,
            [projectUid],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.Result<List<_i5.Task>>>.value(
            _FakeResult_0<List<_i5.Task>>(
          this,
          Invocation.method(
            #getByProject,
            [projectUid],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i5.Task>>>);

  @override
  _i4.Future<_i2.Result<List<_i5.Task>>> getTasksWithDueDate(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTasksWithDueDate,
          [date],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i5.Task>>>.value(
            _FakeResult_0<List<_i5.Task>>(
          this,
          Invocation.method(
            #getTasksWithDueDate,
            [date],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.Result<List<_i5.Task>>>.value(
            _FakeResult_0<List<_i5.Task>>(
          this,
          Invocation.method(
            #getTasksWithDueDate,
            [date],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i5.Task>>>);

  @override
  _i4.Future<_i2.Result<List<_i5.Task>>> getTasksWithoutDueDate() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTasksWithoutDueDate,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i5.Task>>>.value(
            _FakeResult_0<List<_i5.Task>>(
          this,
          Invocation.method(
            #getTasksWithoutDueDate,
            [],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.Result<List<_i5.Task>>>.value(
            _FakeResult_0<List<_i5.Task>>(
          this,
          Invocation.method(
            #getTasksWithoutDueDate,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i5.Task>>>);

  @override
  _i4.Future<_i2.Result<List<_i5.Task>>> getUnregisteredTasks() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnregisteredTasks,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i5.Task>>>.value(
            _FakeResult_0<List<_i5.Task>>(
          this,
          Invocation.method(
            #getUnregisteredTasks,
            [],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.Result<List<_i5.Task>>>.value(
            _FakeResult_0<List<_i5.Task>>(
          this,
          Invocation.method(
            #getUnregisteredTasks,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i5.Task>>>);

  @override
  _i4.Future<_i2.Result<void>> save(_i5.Task? task) => (super.noSuchMethod(
        Invocation.method(
          #save,
          [task],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #save,
            [task],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #save,
            [task],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<void>> delete(String? uid) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [uid],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #delete,
            [uid],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #delete,
            [uid],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Stream<List<_i5.Task>> watchTasks() => (super.noSuchMethod(
        Invocation.method(
          #watchTasks,
          [],
        ),
        returnValue: _i4.Stream<List<_i5.Task>>.empty(),
        returnValueForMissingStub: _i4.Stream<List<_i5.Task>>.empty(),
      ) as _i4.Stream<List<_i5.Task>>);
}
