// Mocks generated by Mockito 5.4.5 from annotations
// in towdow_app/test/viewmodels/caldav_settings_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:towdow_app/core/result.dart' as _i2;
import 'package:towdow_app/data/models/caldav_account.dart' as _i5;
import 'package:towdow_app/data/models/task_calendar.dart' as _i7;
import 'package:towdow_app/data/repositories/account_repository.dart' as _i3;
import 'package:towdow_app/data/repositories/calendar_repository.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AccountRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountRepository extends _i1.Mock implements _i3.AccountRepository {
  MockAccountRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<List<_i5.CaldavAccount>>> getAll() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i5.CaldavAccount>>>.value(
            _FakeResult_0<List<_i5.CaldavAccount>>(
          this,
          Invocation.method(
            #getAll,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i5.CaldavAccount>>>);

  @override
  _i4.Future<_i2.Result<_i5.CaldavAccount?>> getActiveAccount() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveAccount,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<_i5.CaldavAccount?>>.value(
            _FakeResult_0<_i5.CaldavAccount?>(
          this,
          Invocation.method(
            #getActiveAccount,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i5.CaldavAccount?>>);

  @override
  _i4.Future<_i2.Result<void>> save(_i5.CaldavAccount? account) =>
      (super.noSuchMethod(
        Invocation.method(
          #save,
          [account],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #save,
            [account],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<void>> delete(String? accountId) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [accountId],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #delete,
            [accountId],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<void>> setActiveAccount(String? accountId) =>
      (super.noSuchMethod(
        Invocation.method(
          #setActiveAccount,
          [accountId],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #setActiveAccount,
            [accountId],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<bool>> hasActiveAccount() => (super.noSuchMethod(
        Invocation.method(
          #hasActiveAccount,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<bool>>.value(_FakeResult_0<bool>(
          this,
          Invocation.method(
            #hasActiveAccount,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<bool>>);
}

/// A class which mocks [CalendarRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalendarRepository extends _i1.Mock
    implements _i6.CalendarRepository {
  MockCalendarRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<List<_i7.TaskCalendar>>> getAll() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i7.TaskCalendar>>>.value(
            _FakeResult_0<List<_i7.TaskCalendar>>(
          this,
          Invocation.method(
            #getAll,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i7.TaskCalendar>>>);

  @override
  _i4.Future<_i2.Result<_i7.TaskCalendar?>> getById(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getById,
          [uid],
        ),
        returnValue: _i4.Future<_i2.Result<_i7.TaskCalendar?>>.value(
            _FakeResult_0<_i7.TaskCalendar?>(
          this,
          Invocation.method(
            #getById,
            [uid],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i7.TaskCalendar?>>);

  @override
  _i4.Future<_i2.Result<_i7.TaskCalendar?>> getByPath(String? path) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByPath,
          [path],
        ),
        returnValue: _i4.Future<_i2.Result<_i7.TaskCalendar?>>.value(
            _FakeResult_0<_i7.TaskCalendar?>(
          this,
          Invocation.method(
            #getByPath,
            [path],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i7.TaskCalendar?>>);

  @override
  _i4.Future<_i2.Result<void>> save(_i7.TaskCalendar? calendar) =>
      (super.noSuchMethod(
        Invocation.method(
          #save,
          [calendar],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #save,
            [calendar],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<void>> delete(String? uid) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [uid],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #delete,
            [uid],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Stream<List<_i7.TaskCalendar>> watchCalendars() => (super.noSuchMethod(
        Invocation.method(
          #watchCalendars,
          [],
        ),
        returnValue: _i4.Stream<List<_i7.TaskCalendar>>.empty(),
      ) as _i4.Stream<List<_i7.TaskCalendar>>);

  @override
  _i4.Future<_i2.Result<List<_i7.TaskCalendar>>> getProjectCalendars() =>
      (super.noSuchMethod(
        Invocation.method(
          #getProjectCalendars,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i7.TaskCalendar>>>.value(
            _FakeResult_0<List<_i7.TaskCalendar>>(
          this,
          Invocation.method(
            #getProjectCalendars,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i7.TaskCalendar>>>);

  @override
  _i4.Future<_i2.Result<List<_i7.TaskCalendar>>> getCalendarsByDomain(
          String? domain) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCalendarsByDomain,
          [domain],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i7.TaskCalendar>>>.value(
            _FakeResult_0<List<_i7.TaskCalendar>>(
          this,
          Invocation.method(
            #getCalendarsByDomain,
            [domain],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i7.TaskCalendar>>>);

  @override
  _i4.Future<_i2.Result<List<String>>> getUniqueDomains() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUniqueDomains,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<List<String>>>.value(
            _FakeResult_0<List<String>>(
          this,
          Invocation.method(
            #getUniqueDomains,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<String>>>);

  @override
  _i4.Future<_i2.Result<void>> renameDomain(
    String? oldDomain,
    String? newDomain,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #renameDomain,
          [
            oldDomain,
            newDomain,
          ],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #renameDomain,
            [
              oldDomain,
              newDomain,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<Map<String, int>>> getDomainStatistics() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDomainStatistics,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<Map<String, int>>>.value(
            _FakeResult_0<Map<String, int>>(
          this,
          Invocation.method(
            #getDomainStatistics,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<Map<String, int>>>);

  @override
  _i4.Future<_i2.Result<List<_i7.TaskCalendar>>> getCalendarsWithoutDomain() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCalendarsWithoutDomain,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i7.TaskCalendar>>>.value(
            _FakeResult_0<List<_i7.TaskCalendar>>(
          this,
          Invocation.method(
            #getCalendarsWithoutDomain,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i7.TaskCalendar>>>);

  @override
  _i4.Future<_i2.Result<List<_i7.TaskCalendar>>> getCalendarsByStatus(
          String? status) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCalendarsByStatus,
          [status],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i7.TaskCalendar>>>.value(
            _FakeResult_0<List<_i7.TaskCalendar>>(
          this,
          Invocation.method(
            #getCalendarsByStatus,
            [status],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i7.TaskCalendar>>>);

  @override
  _i4.Future<_i2.Result<List<String>>> getUniqueStatuses() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUniqueStatuses,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<List<String>>>.value(
            _FakeResult_0<List<String>>(
          this,
          Invocation.method(
            #getUniqueStatuses,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<String>>>);

  @override
  _i4.Future<_i2.Result<void>> changeStatus(
    String? oldStatus,
    String? newStatus,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #changeStatus,
          [
            oldStatus,
            newStatus,
          ],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #changeStatus,
            [
              oldStatus,
              newStatus,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<Map<String, int>>> getStatusStatistics() =>
      (super.noSuchMethod(
        Invocation.method(
          #getStatusStatistics,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<Map<String, int>>>.value(
            _FakeResult_0<Map<String, int>>(
          this,
          Invocation.method(
            #getStatusStatistics,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<Map<String, int>>>);

  @override
  _i4.Future<_i2.Result<List<_i7.TaskCalendar>>> getCalendarsWithoutStatus() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCalendarsWithoutStatus,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i7.TaskCalendar>>>.value(
            _FakeResult_0<List<_i7.TaskCalendar>>(
          this,
          Invocation.method(
            #getCalendarsWithoutStatus,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i7.TaskCalendar>>>);

  @override
  _i4.Future<_i2.Result<List<_i7.TaskCalendar>>> getArchivedCalendars() =>
      (super.noSuchMethod(
        Invocation.method(
          #getArchivedCalendars,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i7.TaskCalendar>>>.value(
            _FakeResult_0<List<_i7.TaskCalendar>>(
          this,
          Invocation.method(
            #getArchivedCalendars,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i7.TaskCalendar>>>);

  @override
  _i4.Future<_i2.Result<List<_i7.TaskCalendar>>> getActiveCalendars() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveCalendars,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i7.TaskCalendar>>>.value(
            _FakeResult_0<List<_i7.TaskCalendar>>(
          this,
          Invocation.method(
            #getActiveCalendars,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i7.TaskCalendar>>>);
}
