// Mocks generated by Mockito 5.4.5 from annotations
// in towdow_app/test/viewmodels/calendar_selection_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:hive_flutter/hive_flutter.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:towdow_app/core/result.dart' as _i3;
import 'package:towdow_app/data/models/caldav_account.dart' as _i2;
import 'package:towdow_app/data/models/task.dart' as _i6;
import 'package:towdow_app/data/models/task_calendar.dart' as _i7;
import 'package:towdow_app/data/repositories/account_repository.dart' as _i9;
import 'package:towdow_app/data/repositories/calendar_repository.dart' as _i10;
import 'package:towdow_app/data/services/caldav_service.dart' as _i4;
import 'package:towdow_app/data/services/capability_discovery_service.dart'
    as _i8;
import 'package:towdow_app/data/services/local_storage_service.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCaldavAccount_0 extends _i1.SmartFake implements _i2.CaldavAccount {
  _FakeCaldavAccount_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResult_1<T> extends _i1.SmartFake implements _i3.Result<T> {
  _FakeResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CalDAVService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalDAVService extends _i1.Mock implements _i4.CalDAVService {
  MockCalDAVService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CaldavAccount get account => (super.noSuchMethod(
        Invocation.getter(#account),
        returnValue: _FakeCaldavAccount_0(
          this,
          Invocation.getter(#account),
        ),
      ) as _i2.CaldavAccount);

  @override
  _i5.Future<_i3.Result<_i4.CalDAVCapabilities>> testConnection() =>
      (super.noSuchMethod(
        Invocation.method(
          #testConnection,
          [],
        ),
        returnValue: _i5.Future<_i3.Result<_i4.CalDAVCapabilities>>.value(
            _FakeResult_1<_i4.CalDAVCapabilities>(
          this,
          Invocation.method(
            #testConnection,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Result<_i4.CalDAVCapabilities>>);

  @override
  _i5.Future<_i3.Result<String>> createTask(
    _i6.Task? task, {
    String? calendarPath,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTask,
          [task],
          {#calendarPath: calendarPath},
        ),
        returnValue: _i5.Future<_i3.Result<String>>.value(_FakeResult_1<String>(
          this,
          Invocation.method(
            #createTask,
            [task],
            {#calendarPath: calendarPath},
          ),
        )),
      ) as _i5.Future<_i3.Result<String>>);

  @override
  _i5.Future<_i3.Result<void>> updateTask(
    _i6.Task? task,
    String? taskUrl, {
    String? etag,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTask,
          [
            task,
            taskUrl,
          ],
          {#etag: etag},
        ),
        returnValue: _i5.Future<_i3.Result<void>>.value(_FakeResult_1<void>(
          this,
          Invocation.method(
            #updateTask,
            [
              task,
              taskUrl,
            ],
            {#etag: etag},
          ),
        )),
      ) as _i5.Future<_i3.Result<void>>);

  @override
  _i5.Future<_i3.Result<void>> deleteTask(
    String? taskUrl, {
    String? etag,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteTask,
          [taskUrl],
          {#etag: etag},
        ),
        returnValue: _i5.Future<_i3.Result<void>>.value(_FakeResult_1<void>(
          this,
          Invocation.method(
            #deleteTask,
            [taskUrl],
            {#etag: etag},
          ),
        )),
      ) as _i5.Future<_i3.Result<void>>);

  @override
  _i5.Future<_i3.Result<List<_i6.Task>>> fetchTasks({String? calendarPath}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchTasks,
          [],
          {#calendarPath: calendarPath},
        ),
        returnValue: _i5.Future<_i3.Result<List<_i6.Task>>>.value(
            _FakeResult_1<List<_i6.Task>>(
          this,
          Invocation.method(
            #fetchTasks,
            [],
            {#calendarPath: calendarPath},
          ),
        )),
      ) as _i5.Future<_i3.Result<List<_i6.Task>>>);

  @override
  _i5.Future<_i3.Result<_i4.CalDAVCapabilities>> discoverCapabilities() =>
      (super.noSuchMethod(
        Invocation.method(
          #discoverCapabilities,
          [],
        ),
        returnValue: _i5.Future<_i3.Result<_i4.CalDAVCapabilities>>.value(
            _FakeResult_1<_i4.CalDAVCapabilities>(
          this,
          Invocation.method(
            #discoverCapabilities,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Result<_i4.CalDAVCapabilities>>);

  @override
  _i5.Future<_i3.Result<void>> deleteCalendar(String? calendarPath) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCalendar,
          [calendarPath],
        ),
        returnValue: _i5.Future<_i3.Result<void>>.value(_FakeResult_1<void>(
          this,
          Invocation.method(
            #deleteCalendar,
            [calendarPath],
          ),
        )),
      ) as _i5.Future<_i3.Result<void>>);

  @override
  _i5.Future<_i3.Result<_i7.TaskCalendar>> createCalendar({
    required String? displayName,
    String? description,
    String? uid,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCalendar,
          [],
          {
            #displayName: displayName,
            #description: description,
            #uid: uid,
          },
        ),
        returnValue: _i5.Future<_i3.Result<_i7.TaskCalendar>>.value(
            _FakeResult_1<_i7.TaskCalendar>(
          this,
          Invocation.method(
            #createCalendar,
            [],
            {
              #displayName: displayName,
              #description: description,
              #uid: uid,
            },
          ),
        )),
      ) as _i5.Future<_i3.Result<_i7.TaskCalendar>>);

  @override
  _i5.Future<_i3.Result<void>> updateCalendarProperties(
          _i7.TaskCalendar? calendar) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCalendarProperties,
          [calendar],
        ),
        returnValue: _i5.Future<_i3.Result<void>>.value(_FakeResult_1<void>(
          this,
          Invocation.method(
            #updateCalendarProperties,
            [calendar],
          ),
        )),
      ) as _i5.Future<_i3.Result<void>>);
}

/// A class which mocks [CapabilityDiscoveryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCapabilityDiscoveryService extends _i1.Mock
    implements _i8.CapabilityDiscoveryService {
  MockCapabilityDiscoveryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CaldavAccount get account => (super.noSuchMethod(
        Invocation.getter(#account),
        returnValue: _FakeCaldavAccount_0(
          this,
          Invocation.getter(#account),
        ),
      ) as _i2.CaldavAccount);

  @override
  _i5.Future<_i3.Result<_i8.DiscoveryResult>> discoverCapabilities() =>
      (super.noSuchMethod(
        Invocation.method(
          #discoverCapabilities,
          [],
        ),
        returnValue: _i5.Future<_i3.Result<_i8.DiscoveryResult>>.value(
            _FakeResult_1<_i8.DiscoveryResult>(
          this,
          Invocation.method(
            #discoverCapabilities,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Result<_i8.DiscoveryResult>>);
}

/// A class which mocks [AccountRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountRepository extends _i1.Mock implements _i9.AccountRepository {
  MockAccountRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Result<List<_i2.CaldavAccount>>> getAll() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i5.Future<_i3.Result<List<_i2.CaldavAccount>>>.value(
            _FakeResult_1<List<_i2.CaldavAccount>>(
          this,
          Invocation.method(
            #getAll,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Result<List<_i2.CaldavAccount>>>);

  @override
  _i5.Future<_i3.Result<_i2.CaldavAccount?>> getActiveAccount() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveAccount,
          [],
        ),
        returnValue: _i5.Future<_i3.Result<_i2.CaldavAccount?>>.value(
            _FakeResult_1<_i2.CaldavAccount?>(
          this,
          Invocation.method(
            #getActiveAccount,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Result<_i2.CaldavAccount?>>);

  @override
  _i5.Future<_i3.Result<void>> save(_i2.CaldavAccount? account) =>
      (super.noSuchMethod(
        Invocation.method(
          #save,
          [account],
        ),
        returnValue: _i5.Future<_i3.Result<void>>.value(_FakeResult_1<void>(
          this,
          Invocation.method(
            #save,
            [account],
          ),
        )),
      ) as _i5.Future<_i3.Result<void>>);

  @override
  _i5.Future<_i3.Result<void>> delete(String? accountId) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [accountId],
        ),
        returnValue: _i5.Future<_i3.Result<void>>.value(_FakeResult_1<void>(
          this,
          Invocation.method(
            #delete,
            [accountId],
          ),
        )),
      ) as _i5.Future<_i3.Result<void>>);

  @override
  _i5.Future<_i3.Result<void>> setActiveAccount(String? accountId) =>
      (super.noSuchMethod(
        Invocation.method(
          #setActiveAccount,
          [accountId],
        ),
        returnValue: _i5.Future<_i3.Result<void>>.value(_FakeResult_1<void>(
          this,
          Invocation.method(
            #setActiveAccount,
            [accountId],
          ),
        )),
      ) as _i5.Future<_i3.Result<void>>);

  @override
  _i5.Future<_i3.Result<bool>> hasActiveAccount() => (super.noSuchMethod(
        Invocation.method(
          #hasActiveAccount,
          [],
        ),
        returnValue: _i5.Future<_i3.Result<bool>>.value(_FakeResult_1<bool>(
          this,
          Invocation.method(
            #hasActiveAccount,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Result<bool>>);
}

/// A class which mocks [CalendarRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalendarRepository extends _i1.Mock
    implements _i10.CalendarRepository {
  MockCalendarRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Result<List<_i7.TaskCalendar>>> getAll() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i5.Future<_i3.Result<List<_i7.TaskCalendar>>>.value(
            _FakeResult_1<List<_i7.TaskCalendar>>(
          this,
          Invocation.method(
            #getAll,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Result<List<_i7.TaskCalendar>>>);

  @override
  _i5.Future<_i3.Result<_i7.TaskCalendar?>> getById(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getById,
          [uid],
        ),
        returnValue: _i5.Future<_i3.Result<_i7.TaskCalendar?>>.value(
            _FakeResult_1<_i7.TaskCalendar?>(
          this,
          Invocation.method(
            #getById,
            [uid],
          ),
        )),
      ) as _i5.Future<_i3.Result<_i7.TaskCalendar?>>);

  @override
  _i5.Future<_i3.Result<_i7.TaskCalendar?>> getByPath(String? path) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByPath,
          [path],
        ),
        returnValue: _i5.Future<_i3.Result<_i7.TaskCalendar?>>.value(
            _FakeResult_1<_i7.TaskCalendar?>(
          this,
          Invocation.method(
            #getByPath,
            [path],
          ),
        )),
      ) as _i5.Future<_i3.Result<_i7.TaskCalendar?>>);

  @override
  _i5.Future<_i3.Result<void>> save(_i7.TaskCalendar? calendar) =>
      (super.noSuchMethod(
        Invocation.method(
          #save,
          [calendar],
        ),
        returnValue: _i5.Future<_i3.Result<void>>.value(_FakeResult_1<void>(
          this,
          Invocation.method(
            #save,
            [calendar],
          ),
        )),
      ) as _i5.Future<_i3.Result<void>>);

  @override
  _i5.Future<_i3.Result<void>> delete(String? uid) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [uid],
        ),
        returnValue: _i5.Future<_i3.Result<void>>.value(_FakeResult_1<void>(
          this,
          Invocation.method(
            #delete,
            [uid],
          ),
        )),
      ) as _i5.Future<_i3.Result<void>>);

  @override
  _i5.Stream<List<_i7.TaskCalendar>> watchCalendars() => (super.noSuchMethod(
        Invocation.method(
          #watchCalendars,
          [],
        ),
        returnValue: _i5.Stream<List<_i7.TaskCalendar>>.empty(),
      ) as _i5.Stream<List<_i7.TaskCalendar>>);

  @override
  _i5.Future<_i3.Result<List<_i7.TaskCalendar>>> getProjectCalendars() =>
      (super.noSuchMethod(
        Invocation.method(
          #getProjectCalendars,
          [],
        ),
        returnValue: _i5.Future<_i3.Result<List<_i7.TaskCalendar>>>.value(
            _FakeResult_1<List<_i7.TaskCalendar>>(
          this,
          Invocation.method(
            #getProjectCalendars,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Result<List<_i7.TaskCalendar>>>);

  @override
  _i5.Future<_i3.Result<List<_i7.TaskCalendar>>> getCalendarsByDomain(
          String? domain) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCalendarsByDomain,
          [domain],
        ),
        returnValue: _i5.Future<_i3.Result<List<_i7.TaskCalendar>>>.value(
            _FakeResult_1<List<_i7.TaskCalendar>>(
          this,
          Invocation.method(
            #getCalendarsByDomain,
            [domain],
          ),
        )),
      ) as _i5.Future<_i3.Result<List<_i7.TaskCalendar>>>);

  @override
  _i5.Future<_i3.Result<List<String>>> getUniqueDomains() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUniqueDomains,
          [],
        ),
        returnValue: _i5.Future<_i3.Result<List<String>>>.value(
            _FakeResult_1<List<String>>(
          this,
          Invocation.method(
            #getUniqueDomains,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Result<List<String>>>);

  @override
  _i5.Future<_i3.Result<void>> renameDomain(
    String? oldDomain,
    String? newDomain,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #renameDomain,
          [
            oldDomain,
            newDomain,
          ],
        ),
        returnValue: _i5.Future<_i3.Result<void>>.value(_FakeResult_1<void>(
          this,
          Invocation.method(
            #renameDomain,
            [
              oldDomain,
              newDomain,
            ],
          ),
        )),
      ) as _i5.Future<_i3.Result<void>>);

  @override
  _i5.Future<_i3.Result<Map<String, int>>> getDomainStatistics() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDomainStatistics,
          [],
        ),
        returnValue: _i5.Future<_i3.Result<Map<String, int>>>.value(
            _FakeResult_1<Map<String, int>>(
          this,
          Invocation.method(
            #getDomainStatistics,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Result<Map<String, int>>>);

  @override
  _i5.Future<_i3.Result<List<_i7.TaskCalendar>>> getCalendarsWithoutDomain() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCalendarsWithoutDomain,
          [],
        ),
        returnValue: _i5.Future<_i3.Result<List<_i7.TaskCalendar>>>.value(
            _FakeResult_1<List<_i7.TaskCalendar>>(
          this,
          Invocation.method(
            #getCalendarsWithoutDomain,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Result<List<_i7.TaskCalendar>>>);

  @override
  _i5.Future<_i3.Result<List<_i7.TaskCalendar>>> getCalendarsByStatus(
          String? status) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCalendarsByStatus,
          [status],
        ),
        returnValue: _i5.Future<_i3.Result<List<_i7.TaskCalendar>>>.value(
            _FakeResult_1<List<_i7.TaskCalendar>>(
          this,
          Invocation.method(
            #getCalendarsByStatus,
            [status],
          ),
        )),
      ) as _i5.Future<_i3.Result<List<_i7.TaskCalendar>>>);

  @override
  _i5.Future<_i3.Result<List<String>>> getUniqueStatuses() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUniqueStatuses,
          [],
        ),
        returnValue: _i5.Future<_i3.Result<List<String>>>.value(
            _FakeResult_1<List<String>>(
          this,
          Invocation.method(
            #getUniqueStatuses,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Result<List<String>>>);

  @override
  _i5.Future<_i3.Result<void>> changeStatus(
    String? oldStatus,
    String? newStatus,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #changeStatus,
          [
            oldStatus,
            newStatus,
          ],
        ),
        returnValue: _i5.Future<_i3.Result<void>>.value(_FakeResult_1<void>(
          this,
          Invocation.method(
            #changeStatus,
            [
              oldStatus,
              newStatus,
            ],
          ),
        )),
      ) as _i5.Future<_i3.Result<void>>);

  @override
  _i5.Future<_i3.Result<Map<String, int>>> getStatusStatistics() =>
      (super.noSuchMethod(
        Invocation.method(
          #getStatusStatistics,
          [],
        ),
        returnValue: _i5.Future<_i3.Result<Map<String, int>>>.value(
            _FakeResult_1<Map<String, int>>(
          this,
          Invocation.method(
            #getStatusStatistics,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Result<Map<String, int>>>);

  @override
  _i5.Future<_i3.Result<List<_i7.TaskCalendar>>> getCalendarsWithoutStatus() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCalendarsWithoutStatus,
          [],
        ),
        returnValue: _i5.Future<_i3.Result<List<_i7.TaskCalendar>>>.value(
            _FakeResult_1<List<_i7.TaskCalendar>>(
          this,
          Invocation.method(
            #getCalendarsWithoutStatus,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Result<List<_i7.TaskCalendar>>>);

  @override
  _i5.Future<_i3.Result<List<_i7.TaskCalendar>>> getArchivedCalendars() =>
      (super.noSuchMethod(
        Invocation.method(
          #getArchivedCalendars,
          [],
        ),
        returnValue: _i5.Future<_i3.Result<List<_i7.TaskCalendar>>>.value(
            _FakeResult_1<List<_i7.TaskCalendar>>(
          this,
          Invocation.method(
            #getArchivedCalendars,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Result<List<_i7.TaskCalendar>>>);

  @override
  _i5.Future<_i3.Result<List<_i7.TaskCalendar>>> getActiveCalendars() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveCalendars,
          [],
        ),
        returnValue: _i5.Future<_i3.Result<List<_i7.TaskCalendar>>>.value(
            _FakeResult_1<List<_i7.TaskCalendar>>(
          this,
          Invocation.method(
            #getActiveCalendars,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Result<List<_i7.TaskCalendar>>>);
}

/// A class which mocks [LocalStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorageService extends _i1.Mock
    implements _i11.LocalStorageService {
  MockLocalStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Result<void>> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<_i3.Result<void>>.value(_FakeResult_1<void>(
          this,
          Invocation.method(
            #initialize,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Result<void>>);

  @override
  _i5.Future<_i3.Result<List<T>>> getAll<T>(String? boxName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [boxName],
        ),
        returnValue:
            _i5.Future<_i3.Result<List<T>>>.value(_FakeResult_1<List<T>>(
          this,
          Invocation.method(
            #getAll,
            [boxName],
          ),
        )),
      ) as _i5.Future<_i3.Result<List<T>>>);

  @override
  _i5.Future<_i3.Result<void>> put<T>(
    String? boxName,
    String? key,
    T? item,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            boxName,
            key,
            item,
          ],
        ),
        returnValue: _i5.Future<_i3.Result<void>>.value(_FakeResult_1<void>(
          this,
          Invocation.method(
            #put,
            [
              boxName,
              key,
              item,
            ],
          ),
        )),
      ) as _i5.Future<_i3.Result<void>>);

  @override
  _i5.Future<_i3.Result<T?>> get<T>(
    String? boxName,
    String? key,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [
            boxName,
            key,
          ],
        ),
        returnValue: _i5.Future<_i3.Result<T?>>.value(_FakeResult_1<T?>(
          this,
          Invocation.method(
            #get,
            [
              boxName,
              key,
            ],
          ),
        )),
      ) as _i5.Future<_i3.Result<T?>>);

  @override
  _i5.Future<_i3.Result<void>> delete(
    String? boxName,
    String? key,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [
            boxName,
            key,
          ],
        ),
        returnValue: _i5.Future<_i3.Result<void>>.value(_FakeResult_1<void>(
          this,
          Invocation.method(
            #delete,
            [
              boxName,
              key,
            ],
          ),
        )),
      ) as _i5.Future<_i3.Result<void>>);

  @override
  _i5.Stream<_i12.BoxEvent> getStream(String? boxName) => (super.noSuchMethod(
        Invocation.method(
          #getStream,
          [boxName],
        ),
        returnValue: _i5.Stream<_i12.BoxEvent>.empty(),
      ) as _i5.Stream<_i12.BoxEvent>);

  @override
  _i5.Future<_i3.Result<void>> clear(String? boxName) => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [boxName],
        ),
        returnValue: _i5.Future<_i3.Result<void>>.value(_FakeResult_1<void>(
          this,
          Invocation.method(
            #clear,
            [boxName],
          ),
        )),
      ) as _i5.Future<_i3.Result<void>>);

  @override
  _i5.Future<_i3.Result<void>> fixCorruptedData() => (super.noSuchMethod(
        Invocation.method(
          #fixCorruptedData,
          [],
        ),
        returnValue: _i5.Future<_i3.Result<void>>.value(_FakeResult_1<void>(
          this,
          Invocation.method(
            #fixCorruptedData,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Result<void>>);

  @override
  _i5.Future<_i3.Result<void>> clearAllData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValue: _i5.Future<_i3.Result<void>>.value(_FakeResult_1<void>(
          this,
          Invocation.method(
            #clearAllData,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Result<void>>);

  @override
  _i5.Future<_i3.Result<void>> emergencyReset() => (super.noSuchMethod(
        Invocation.method(
          #emergencyReset,
          [],
        ),
        returnValue: _i5.Future<_i3.Result<void>>.value(_FakeResult_1<void>(
          this,
          Invocation.method(
            #emergencyReset,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Result<void>>);

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> debugAllBoxes() => (super.noSuchMethod(
        Invocation.method(
          #debugAllBoxes,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.Result<List<String>>> getAllDomains() => (super.noSuchMethod(
        Invocation.method(
          #getAllDomains,
          [],
        ),
        returnValue: _i5.Future<_i3.Result<List<String>>>.value(
            _FakeResult_1<List<String>>(
          this,
          Invocation.method(
            #getAllDomains,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Result<List<String>>>);

  @override
  _i5.Future<_i3.Result<void>> addDomain(String? domain) => (super.noSuchMethod(
        Invocation.method(
          #addDomain,
          [domain],
        ),
        returnValue: _i5.Future<_i3.Result<void>>.value(_FakeResult_1<void>(
          this,
          Invocation.method(
            #addDomain,
            [domain],
          ),
        )),
      ) as _i5.Future<_i3.Result<void>>);

  @override
  _i5.Future<_i3.Result<void>> removeDomain(String? domain) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeDomain,
          [domain],
        ),
        returnValue: _i5.Future<_i3.Result<void>>.value(_FakeResult_1<void>(
          this,
          Invocation.method(
            #removeDomain,
            [domain],
          ),
        )),
      ) as _i5.Future<_i3.Result<void>>);

  @override
  _i5.Future<_i3.Result<bool>> domainExists(String? domain) =>
      (super.noSuchMethod(
        Invocation.method(
          #domainExists,
          [domain],
        ),
        returnValue: _i5.Future<_i3.Result<bool>>.value(_FakeResult_1<bool>(
          this,
          Invocation.method(
            #domainExists,
            [domain],
          ),
        )),
      ) as _i5.Future<_i3.Result<bool>>);

  @override
  _i5.Future<_i3.Result<void>> renameDomain(
    String? oldDomain,
    String? newDomain,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #renameDomain,
          [
            oldDomain,
            newDomain,
          ],
        ),
        returnValue: _i5.Future<_i3.Result<void>>.value(_FakeResult_1<void>(
          this,
          Invocation.method(
            #renameDomain,
            [
              oldDomain,
              newDomain,
            ],
          ),
        )),
      ) as _i5.Future<_i3.Result<void>>);

  @override
  _i5.Future<_i3.Result<List<String>>> getAllStatuses() => (super.noSuchMethod(
        Invocation.method(
          #getAllStatuses,
          [],
        ),
        returnValue: _i5.Future<_i3.Result<List<String>>>.value(
            _FakeResult_1<List<String>>(
          this,
          Invocation.method(
            #getAllStatuses,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Result<List<String>>>);

  @override
  _i5.Future<_i3.Result<void>> addStatus(String? status) => (super.noSuchMethod(
        Invocation.method(
          #addStatus,
          [status],
        ),
        returnValue: _i5.Future<_i3.Result<void>>.value(_FakeResult_1<void>(
          this,
          Invocation.method(
            #addStatus,
            [status],
          ),
        )),
      ) as _i5.Future<_i3.Result<void>>);

  @override
  _i5.Future<_i3.Result<void>> removeStatus(String? status) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeStatus,
          [status],
        ),
        returnValue: _i5.Future<_i3.Result<void>>.value(_FakeResult_1<void>(
          this,
          Invocation.method(
            #removeStatus,
            [status],
          ),
        )),
      ) as _i5.Future<_i3.Result<void>>);

  @override
  _i5.Future<_i3.Result<bool>> statusExists(String? status) =>
      (super.noSuchMethod(
        Invocation.method(
          #statusExists,
          [status],
        ),
        returnValue: _i5.Future<_i3.Result<bool>>.value(_FakeResult_1<bool>(
          this,
          Invocation.method(
            #statusExists,
            [status],
          ),
        )),
      ) as _i5.Future<_i3.Result<bool>>);

  @override
  _i5.Future<_i3.Result<void>> renameStatus(
    String? oldStatus,
    String? newStatus,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #renameStatus,
          [
            oldStatus,
            newStatus,
          ],
        ),
        returnValue: _i5.Future<_i3.Result<void>>.value(_FakeResult_1<void>(
          this,
          Invocation.method(
            #renameStatus,
            [
              oldStatus,
              newStatus,
            ],
          ),
        )),
      ) as _i5.Future<_i3.Result<void>>);
}
