// Mocks generated by Mockito 5.4.5 from annotations
// in flowit_app/test/viewmodels/navbar_sync_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flowit_app/core/result.dart' as _i2;
import 'package:flowit_app/data/models/caldav_account.dart' as _i5;
import 'package:flowit_app/data/repositories/account_repository.dart' as _i3;
import 'package:flowit_app/data/services/sync_service.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AccountRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountRepository extends _i1.Mock implements _i3.AccountRepository {
  MockAccountRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<List<_i5.CaldavAccount>>> getAll() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i5.CaldavAccount>>>.value(
            _FakeResult_0<List<_i5.CaldavAccount>>(
          this,
          Invocation.method(
            #getAll,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i5.CaldavAccount>>>);

  @override
  _i4.Future<_i2.Result<_i5.CaldavAccount?>> getActiveAccount() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveAccount,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<_i5.CaldavAccount?>>.value(
            _FakeResult_0<_i5.CaldavAccount?>(
          this,
          Invocation.method(
            #getActiveAccount,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i5.CaldavAccount?>>);

  @override
  _i4.Future<_i2.Result<void>> save(_i5.CaldavAccount? account) =>
      (super.noSuchMethod(
        Invocation.method(
          #save,
          [account],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #save,
            [account],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<void>> delete(String? accountId) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [accountId],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #delete,
            [accountId],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<void>> setActiveAccount(String? accountId) =>
      (super.noSuchMethod(
        Invocation.method(
          #setActiveAccount,
          [accountId],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #setActiveAccount,
            [accountId],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<bool>> hasActiveAccount() => (super.noSuchMethod(
        Invocation.method(
          #hasActiveAccount,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<bool>>.value(_FakeResult_0<bool>(
          this,
          Invocation.method(
            #hasActiveAccount,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<bool>>);
}

/// A class which mocks [SyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncService extends _i1.Mock implements _i6.SyncService {
  MockSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i6.SyncStatus> get statusStream => (super.noSuchMethod(
        Invocation.getter(#statusStream),
        returnValue: _i4.Stream<_i6.SyncStatus>.empty(),
      ) as _i4.Stream<_i6.SyncStatus>);

  @override
  _i4.Stream<double> get progressStream => (super.noSuchMethod(
        Invocation.getter(#progressStream),
        returnValue: _i4.Stream<double>.empty(),
      ) as _i4.Stream<double>);

  @override
  _i6.SyncStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i6.SyncStatus.idle,
      ) as _i6.SyncStatus);

  @override
  bool get isBackgroundSyncRunning => (super.noSuchMethod(
        Invocation.getter(#isBackgroundSyncRunning),
        returnValue: false,
      ) as bool);

  @override
  bool get isBackgroundSyncing => (super.noSuchMethod(
        Invocation.getter(#isBackgroundSyncing),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<_i2.Result<void>> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #initialize,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  void startPeriodicSync() => super.noSuchMethod(
        Invocation.method(
          #startPeriodicSync,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void stopPeriodicSync() => super.noSuchMethod(
        Invocation.method(
          #stopPeriodicSync,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<_i2.Result<_i6.SyncResult>> syncNow() => (super.noSuchMethod(
        Invocation.method(
          #syncNow,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<_i6.SyncResult>>.value(
            _FakeResult_0<_i6.SyncResult>(
          this,
          Invocation.method(
            #syncNow,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i6.SyncResult>>);

  @override
  _i4.Future<_i2.Result<void>> queueSyncOperation(
    _i6.SyncOperation? operation,
    String? itemId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #queueSyncOperation,
          [
            operation,
            itemId,
            data,
          ],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #queueSyncOperation,
            [
              operation,
              itemId,
              data,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
