// Mocks generated by Mockito 5.4.5 from annotations
// in towdow_app/test/services/storage/task_attachment_s3_update_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:towdow_app/core/result.dart' as _i2;
import 'package:towdow_app/data/models/journal.dart' as _i7;
import 'package:towdow_app/data/models/task.dart' as _i5;
import 'package:towdow_app/data/repositories/journal_repository.dart' as _i6;
import 'package:towdow_app/data/repositories/task_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRepository extends _i1.Mock implements _i3.TaskRepository {
  MockTaskRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<List<_i5.Task>>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i5.Task>>>.value(
            _FakeResult_0<List<_i5.Task>>(
          this,
          Invocation.method(
            #getAll,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i5.Task>>>);

  @override
  _i4.Future<_i2.Result<_i5.Task?>> getById(String? uid) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [uid],
        ),
        returnValue:
            _i4.Future<_i2.Result<_i5.Task?>>.value(_FakeResult_0<_i5.Task?>(
          this,
          Invocation.method(
            #getById,
            [uid],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i5.Task?>>);

  @override
  _i4.Future<_i2.Result<List<_i5.Task>>> getByProject(String? projectUid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByProject,
          [projectUid],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i5.Task>>>.value(
            _FakeResult_0<List<_i5.Task>>(
          this,
          Invocation.method(
            #getByProject,
            [projectUid],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i5.Task>>>);

  @override
  _i4.Future<_i2.Result<List<_i5.Task>>> getTasksWithDueDate(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTasksWithDueDate,
          [date],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i5.Task>>>.value(
            _FakeResult_0<List<_i5.Task>>(
          this,
          Invocation.method(
            #getTasksWithDueDate,
            [date],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i5.Task>>>);

  @override
  _i4.Future<_i2.Result<List<_i5.Task>>> getTasksWithoutDueDate() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTasksWithoutDueDate,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i5.Task>>>.value(
            _FakeResult_0<List<_i5.Task>>(
          this,
          Invocation.method(
            #getTasksWithoutDueDate,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i5.Task>>>);

  @override
  _i4.Future<_i2.Result<List<_i5.Task>>> getUnregisteredTasks() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnregisteredTasks,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i5.Task>>>.value(
            _FakeResult_0<List<_i5.Task>>(
          this,
          Invocation.method(
            #getUnregisteredTasks,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i5.Task>>>);

  @override
  _i4.Future<_i2.Result<void>> save(_i5.Task? task) => (super.noSuchMethod(
        Invocation.method(
          #save,
          [task],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #save,
            [task],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<void>> delete(String? uid) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [uid],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #delete,
            [uid],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Stream<List<_i5.Task>> watchTasks() => (super.noSuchMethod(
        Invocation.method(
          #watchTasks,
          [],
        ),
        returnValue: _i4.Stream<List<_i5.Task>>.empty(),
      ) as _i4.Stream<List<_i5.Task>>);

  @override
  _i4.Stream<List<_i5.Task>> watchTasksByProject(String? projectPath) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchTasksByProject,
          [projectPath],
        ),
        returnValue: _i4.Stream<List<_i5.Task>>.empty(),
      ) as _i4.Stream<List<_i5.Task>>);

  @override
  _i4.Future<_i2.Result<void>> saveFromSync(_i5.Task? task) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveFromSync,
          [task],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #saveFromSync,
            [task],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<void>> deleteByProjectLocalOnly(String? projectPath) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteByProjectLocalOnly,
          [projectPath],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #deleteByProjectLocalOnly,
            [projectPath],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<void>> deleteOrphanedTasksLocalOnly(
          Set<String>? validCalendarPaths) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteOrphanedTasksLocalOnly,
          [validCalendarPaths],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #deleteOrphanedTasksLocalOnly,
            [validCalendarPaths],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);
}

/// A class which mocks [JournalRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockJournalRepository extends _i1.Mock implements _i6.JournalRepository {
  MockJournalRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<List<_i7.Journal>>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i7.Journal>>>.value(
            _FakeResult_0<List<_i7.Journal>>(
          this,
          Invocation.method(
            #getAll,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i7.Journal>>>);

  @override
  _i4.Future<_i2.Result<_i7.Journal?>> getById(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getById,
          [uid],
        ),
        returnValue: _i4.Future<_i2.Result<_i7.Journal?>>.value(
            _FakeResult_0<_i7.Journal?>(
          this,
          Invocation.method(
            #getById,
            [uid],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i7.Journal?>>);

  @override
  _i4.Future<_i2.Result<List<_i7.Journal>>> getByProject(String? projectUid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByProject,
          [projectUid],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i7.Journal>>>.value(
            _FakeResult_0<List<_i7.Journal>>(
          this,
          Invocation.method(
            #getByProject,
            [projectUid],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i7.Journal>>>);

  @override
  _i4.Future<_i2.Result<void>> save(_i7.Journal? journal) =>
      (super.noSuchMethod(
        Invocation.method(
          #save,
          [journal],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #save,
            [journal],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<void>> delete(String? uid) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [uid],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #delete,
            [uid],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Stream<List<_i7.Journal>> watchJournals() => (super.noSuchMethod(
        Invocation.method(
          #watchJournals,
          [],
        ),
        returnValue: _i4.Stream<List<_i7.Journal>>.empty(),
      ) as _i4.Stream<List<_i7.Journal>>);

  @override
  _i4.Future<_i2.Result<void>> saveFromSync(_i7.Journal? journal) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveFromSync,
          [journal],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #saveFromSync,
            [journal],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);
}
