// Mocks generated by Mockito 5.4.5 from annotations
// in flowit_app/test/integration/sync_delete_flow_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flowit_app/core/result.dart' as _i2;
import 'package:flowit_app/data/models/caldav_account.dart' as _i7;
import 'package:flowit_app/data/models/task.dart' as _i5;
import 'package:flowit_app/data/models/task_calendar.dart' as _i9;
import 'package:flowit_app/data/repositories/account_repository.dart' as _i6;
import 'package:flowit_app/data/repositories/calendar_repository.dart' as _i8;
import 'package:flowit_app/data/repositories/task_repository.dart' as _i3;
import 'package:flowit_app/data/services/local_storage_service.dart' as _i10;
import 'package:hive_flutter/hive_flutter.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRepository extends _i1.Mock implements _i3.TaskRepository {
  @override
  _i4.Future<_i2.Result<List<_i5.Task>>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i5.Task>>>.value(
            _FakeResult_0<List<_i5.Task>>(
          this,
          Invocation.method(
            #getAll,
            [],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.Result<List<_i5.Task>>>.value(
            _FakeResult_0<List<_i5.Task>>(
          this,
          Invocation.method(
            #getAll,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i5.Task>>>);

  @override
  _i4.Future<_i2.Result<_i5.Task?>> getById(String? uid) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [uid],
        ),
        returnValue:
            _i4.Future<_i2.Result<_i5.Task?>>.value(_FakeResult_0<_i5.Task?>(
          this,
          Invocation.method(
            #getById,
            [uid],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<_i5.Task?>>.value(_FakeResult_0<_i5.Task?>(
          this,
          Invocation.method(
            #getById,
            [uid],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i5.Task?>>);

  @override
  _i4.Future<_i2.Result<List<_i5.Task>>> getByProject(String? projectUid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByProject,
          [projectUid],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i5.Task>>>.value(
            _FakeResult_0<List<_i5.Task>>(
          this,
          Invocation.method(
            #getByProject,
            [projectUid],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.Result<List<_i5.Task>>>.value(
            _FakeResult_0<List<_i5.Task>>(
          this,
          Invocation.method(
            #getByProject,
            [projectUid],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i5.Task>>>);

  @override
  _i4.Future<_i2.Result<List<_i5.Task>>> getTasksWithDueDate(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTasksWithDueDate,
          [date],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i5.Task>>>.value(
            _FakeResult_0<List<_i5.Task>>(
          this,
          Invocation.method(
            #getTasksWithDueDate,
            [date],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.Result<List<_i5.Task>>>.value(
            _FakeResult_0<List<_i5.Task>>(
          this,
          Invocation.method(
            #getTasksWithDueDate,
            [date],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i5.Task>>>);

  @override
  _i4.Future<_i2.Result<List<_i5.Task>>> getTasksWithoutDueDate() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTasksWithoutDueDate,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i5.Task>>>.value(
            _FakeResult_0<List<_i5.Task>>(
          this,
          Invocation.method(
            #getTasksWithoutDueDate,
            [],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.Result<List<_i5.Task>>>.value(
            _FakeResult_0<List<_i5.Task>>(
          this,
          Invocation.method(
            #getTasksWithoutDueDate,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i5.Task>>>);

  @override
  _i4.Future<_i2.Result<List<_i5.Task>>> getUnregisteredTasks() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnregisteredTasks,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i5.Task>>>.value(
            _FakeResult_0<List<_i5.Task>>(
          this,
          Invocation.method(
            #getUnregisteredTasks,
            [],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.Result<List<_i5.Task>>>.value(
            _FakeResult_0<List<_i5.Task>>(
          this,
          Invocation.method(
            #getUnregisteredTasks,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i5.Task>>>);

  @override
  _i4.Future<_i2.Result<void>> save(_i5.Task? task) => (super.noSuchMethod(
        Invocation.method(
          #save,
          [task],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #save,
            [task],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #save,
            [task],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<void>> delete(String? uid) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [uid],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #delete,
            [uid],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #delete,
            [uid],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Stream<List<_i5.Task>> watchTasks() => (super.noSuchMethod(
        Invocation.method(
          #watchTasks,
          [],
        ),
        returnValue: _i4.Stream<List<_i5.Task>>.empty(),
        returnValueForMissingStub: _i4.Stream<List<_i5.Task>>.empty(),
      ) as _i4.Stream<List<_i5.Task>>);
}

/// A class which mocks [AccountRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountRepository extends _i1.Mock implements _i6.AccountRepository {
  @override
  _i4.Future<_i2.Result<List<_i7.CaldavAccount>>> getAll() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i7.CaldavAccount>>>.value(
            _FakeResult_0<List<_i7.CaldavAccount>>(
          this,
          Invocation.method(
            #getAll,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<List<_i7.CaldavAccount>>>.value(
                _FakeResult_0<List<_i7.CaldavAccount>>(
          this,
          Invocation.method(
            #getAll,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i7.CaldavAccount>>>);

  @override
  _i4.Future<_i2.Result<_i7.CaldavAccount?>> getActiveAccount() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveAccount,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<_i7.CaldavAccount?>>.value(
            _FakeResult_0<_i7.CaldavAccount?>(
          this,
          Invocation.method(
            #getActiveAccount,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<_i7.CaldavAccount?>>.value(
                _FakeResult_0<_i7.CaldavAccount?>(
          this,
          Invocation.method(
            #getActiveAccount,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i7.CaldavAccount?>>);

  @override
  _i4.Future<_i2.Result<void>> save(_i7.CaldavAccount? account) =>
      (super.noSuchMethod(
        Invocation.method(
          #save,
          [account],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #save,
            [account],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #save,
            [account],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<void>> delete(String? accountId) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [accountId],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #delete,
            [accountId],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #delete,
            [accountId],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<void>> setActiveAccount(String? accountId) =>
      (super.noSuchMethod(
        Invocation.method(
          #setActiveAccount,
          [accountId],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #setActiveAccount,
            [accountId],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #setActiveAccount,
            [accountId],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<bool>> hasActiveAccount() => (super.noSuchMethod(
        Invocation.method(
          #hasActiveAccount,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<bool>>.value(_FakeResult_0<bool>(
          this,
          Invocation.method(
            #hasActiveAccount,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<bool>>.value(_FakeResult_0<bool>(
          this,
          Invocation.method(
            #hasActiveAccount,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<bool>>);
}

/// A class which mocks [CalendarRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalendarRepository extends _i1.Mock
    implements _i8.CalendarRepository {
  @override
  _i4.Future<_i2.Result<List<_i9.TaskCalendar>>> getAll() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i9.TaskCalendar>>>.value(
            _FakeResult_0<List<_i9.TaskCalendar>>(
          this,
          Invocation.method(
            #getAll,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<List<_i9.TaskCalendar>>>.value(
                _FakeResult_0<List<_i9.TaskCalendar>>(
          this,
          Invocation.method(
            #getAll,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i9.TaskCalendar>>>);

  @override
  _i4.Future<_i2.Result<_i9.TaskCalendar?>> getById(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getById,
          [uid],
        ),
        returnValue: _i4.Future<_i2.Result<_i9.TaskCalendar?>>.value(
            _FakeResult_0<_i9.TaskCalendar?>(
          this,
          Invocation.method(
            #getById,
            [uid],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<_i9.TaskCalendar?>>.value(
                _FakeResult_0<_i9.TaskCalendar?>(
          this,
          Invocation.method(
            #getById,
            [uid],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i9.TaskCalendar?>>);

  @override
  _i4.Future<_i2.Result<_i9.TaskCalendar?>> getByPath(String? path) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByPath,
          [path],
        ),
        returnValue: _i4.Future<_i2.Result<_i9.TaskCalendar?>>.value(
            _FakeResult_0<_i9.TaskCalendar?>(
          this,
          Invocation.method(
            #getByPath,
            [path],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<_i9.TaskCalendar?>>.value(
                _FakeResult_0<_i9.TaskCalendar?>(
          this,
          Invocation.method(
            #getByPath,
            [path],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i9.TaskCalendar?>>);

  @override
  _i4.Future<_i2.Result<void>> save(_i9.TaskCalendar? calendar) =>
      (super.noSuchMethod(
        Invocation.method(
          #save,
          [calendar],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #save,
            [calendar],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #save,
            [calendar],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<void>> delete(String? uid) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [uid],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #delete,
            [uid],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #delete,
            [uid],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Stream<List<_i9.TaskCalendar>> watchCalendars() => (super.noSuchMethod(
        Invocation.method(
          #watchCalendars,
          [],
        ),
        returnValue: _i4.Stream<List<_i9.TaskCalendar>>.empty(),
        returnValueForMissingStub: _i4.Stream<List<_i9.TaskCalendar>>.empty(),
      ) as _i4.Stream<List<_i9.TaskCalendar>>);

  @override
  _i4.Future<_i2.Result<List<_i9.TaskCalendar>>> getProjectCalendars() =>
      (super.noSuchMethod(
        Invocation.method(
          #getProjectCalendars,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i9.TaskCalendar>>>.value(
            _FakeResult_0<List<_i9.TaskCalendar>>(
          this,
          Invocation.method(
            #getProjectCalendars,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<List<_i9.TaskCalendar>>>.value(
                _FakeResult_0<List<_i9.TaskCalendar>>(
          this,
          Invocation.method(
            #getProjectCalendars,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i9.TaskCalendar>>>);
}

/// A class which mocks [LocalStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorageService extends _i1.Mock
    implements _i10.LocalStorageService {
  @override
  _i4.Future<_i2.Result<void>> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #initialize,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #initialize,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<List<T>>> getAll<T>(String? boxName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [boxName],
        ),
        returnValue:
            _i4.Future<_i2.Result<List<T>>>.value(_FakeResult_0<List<T>>(
          this,
          Invocation.method(
            #getAll,
            [boxName],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<List<T>>>.value(_FakeResult_0<List<T>>(
          this,
          Invocation.method(
            #getAll,
            [boxName],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<T>>>);

  @override
  _i4.Future<_i2.Result<void>> put<T>(
    String? boxName,
    String? key,
    T? item,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            boxName,
            key,
            item,
          ],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #put,
            [
              boxName,
              key,
              item,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #put,
            [
              boxName,
              key,
              item,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<T?>> get<T>(
    String? boxName,
    String? key,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [
            boxName,
            key,
          ],
        ),
        returnValue: _i4.Future<_i2.Result<T?>>.value(_FakeResult_0<T?>(
          this,
          Invocation.method(
            #get,
            [
              boxName,
              key,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<T?>>.value(_FakeResult_0<T?>(
          this,
          Invocation.method(
            #get,
            [
              boxName,
              key,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Result<T?>>);

  @override
  _i4.Future<_i2.Result<void>> delete(
    String? boxName,
    String? key,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [
            boxName,
            key,
          ],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #delete,
            [
              boxName,
              key,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #delete,
            [
              boxName,
              key,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Stream<_i11.BoxEvent> getStream(String? boxName) => (super.noSuchMethod(
        Invocation.method(
          #getStream,
          [boxName],
        ),
        returnValue: _i4.Stream<_i11.BoxEvent>.empty(),
        returnValueForMissingStub: _i4.Stream<_i11.BoxEvent>.empty(),
      ) as _i4.Stream<_i11.BoxEvent>);

  @override
  _i4.Future<_i2.Result<void>> clear(String? boxName) => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [boxName],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #clear,
            [boxName],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #clear,
            [boxName],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<void>> fixCorruptedData() => (super.noSuchMethod(
        Invocation.method(
          #fixCorruptedData,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #fixCorruptedData,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #fixCorruptedData,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<void>> clearAllData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #clearAllData,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #clearAllData,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<void>> emergencyReset() => (super.noSuchMethod(
        Invocation.method(
          #emergencyReset,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #emergencyReset,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #emergencyReset,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> debugAllBoxes() => (super.noSuchMethod(
        Invocation.method(
          #debugAllBoxes,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
